version: '3.8'

services:
  api:
    build: .
    env_file:
      - ./.env
    depends_on:
      - postgresql-db
    stdin_open: true
    tty: true
    container_name: user-api
    command: sh -c 'npm install && npm run dev'
    ports:
      - $PORT:$PORT
    volumes:
      - .:/usr/users-api
      - /usr/users-api/node_modules


  postgresql-db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - data:/data/db
    tty: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '@12!mypass'
      POSTGRES_DB: 'usersDb'
      DATABASE_URL: "postgresql://postgres:@12!mypass@postgresql-db:5432/usersDb?schema=public"

volumes: 
 data: {}